# Generated by Django 4.2.5 on 2023-09-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=1000)),
                ('cast', models.CharField(max_length=1000)),
                ('director', models.CharField(max_length=1000)),
                ('keywords', models.CharField(max_length=1000)),
                ('overview', models.TextField()),
                ('runtime_minutes', models.IntegerField()),
                ('genres', models.CharField(max_length=1000)),
                ('production_companies', models.CharField(max_length=1000)),
                ('release_date', models.DateField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
