# Generated by Django 4.2.5 on 2023-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='homepage',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
