# Generated by Django 4.2.5 on 2023-10-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_initial_data_load'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
