# Generated by Django 4.2.5 on 2023-10-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_user_moviecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecollection',
            name='movies',
            field=models.ManyToManyField(to='movie.movie'),
        ),
    ]
