# Generated by Django 4.2.5 on 2023-10-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='release_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
